export const APPLICATIONS_DATA = [
  {
    id: 1,
    role: "Senior Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    workType: "Remote",
    appliedDate: "Oct 24, 2023",
    salary: "$180k - $240k",
    status: "Interview",
    initial: "G",
    gradientFrom: "from-blue-500",
    gradientTo: "to-purple-500",
    accentColor: "bg-amber-500/80",
    description:
      "We are looking for a Senior Software Engineer to join our infrastructure team, building highly scalable systems that power billions of users globally.",
    responsibilities: [
      "Design and implement large-scale distributed systems.",
      "Lead technical discussions and drive architecture decisions.",
      "Collaborate with cross-functional teams to deliver product features.",
      "Mentor junior engineers and foster a culture of engineering excellence.",
    ],
    requirements: [
      "7+ years of software engineering experience.",
      "Proficiency in Go, Java, or C++.",
      "Experience with distributed systems and cloud infrastructure.",
      "Strong problem-solving and communication skills.",
    ],
    benefits: [
      "Competitive salary and RSU package.",
      "World-class health benefits.",
      "On-site amenities and flexible remote work.",
      "Annual education reimbursement.",
    ],
    matchScore: 82,
    matchLabel: "High Match",
    matchColor: "text-emerald-500",
    statusHistory: [
      { label: "Interview Scheduled", date: "Oct 27, 2023", icon: "chat_bubble", color: "bg-amber-500" },
      { label: "Application Reviewed", date: "Oct 25, 2023", icon: "check_circle", color: "bg-blue-500" },
      { label: "Applied", date: "Oct 24, 2023", icon: "send", color: "bg-slate-400" },
    ],
  },
  {
    id: 2,
    role: "Frontend Developer",
    company: "Spotify",
    location: "New York, NY",
    workType: "Hybrid",
    appliedDate: "Oct 22, 2023",
    salary: "$140k - $160k",
    status: "Applied",
    initial: "S",
    gradientFrom: "from-green-500",
    gradientTo: "to-teal-500",
    accentColor: "bg-blue-500/80",
    description:
      "Join Spotify's web player team to craft beautiful, performant experiences for music lovers around the world.",
    responsibilities: [
      "Build and maintain the Spotify Web Player using React.",
      "Implement A/B tests and analyze user engagement metrics.",
      "Collaborate with designers to refine the UI/UX.",
      "Champion web performance and accessibility standards.",
    ],
    requirements: [
      "3+ years of React experience.",
      "Strong CSS and animation skills.",
      "Experience with audio APIs is a plus.",
      "Passion for music and creative technology.",
    ],
    benefits: [
      "Free Spotify Premium for life.",
      "Equity and competitive pay.",
      "Flexible hybrid work schedule.",
      "Wellness and learning stipends.",
    ],
    matchScore: 91,
    matchLabel: "Top Match",
    matchColor: "text-emerald-500",
    statusHistory: [
      { label: "Applied", date: "Oct 22, 2023", icon: "send", color: "bg-blue-500" },
    ],
  },
  {
    id: 3,
    role: "Full Stack Engineer",
    company: "Netflix",
    location: "Los Gatos, CA",
    workType: "Remote",
    appliedDate: "Oct 15, 2023",
    salary: "$210k - $280k",
    status: "Offer",
    initial: "N",
    gradientFrom: "from-orange-500",
    gradientTo: "to-red-500",
    accentColor: "bg-emerald-500/80",
    description:
      "Netflix is looking for a Full Stack Engineer to help build the systems that deliver content to 230+ million subscribers worldwide.",
    responsibilities: [
      "Develop robust backend services in Java/Node.js.",
      "Build React-based internal tools and dashboards.",
      "Optimize streaming performance and reliability.",
      "Contribute to open-source projects in the Netflix OSS ecosystem.",
    ],
    requirements: [
      "5+ years full-stack experience.",
      "Strong knowledge of microservices and API design.",
      "Experience with AWS or GCP.",
      "Ability to thrive in a high-performance culture.",
    ],
    benefits: [
      "Industry-leading compensation.",
      "Unlimited vacation policy.",
      "Top-tier health benefits.",
      "Freedom & Responsibility culture.",
    ],
    matchScore: 74,
    matchLabel: "Good Match",
    matchColor: "text-blue-400",
    statusHistory: [
      { label: "Offer Extended", date: "Oct 28, 2023", icon: "workspace_premium", color: "bg-emerald-500" },
      { label: "Final Interview", date: "Oct 20, 2023", icon: "chat_bubble", color: "bg-amber-500" },
      { label: "Phone Screen", date: "Oct 18, 2023", icon: "phone", color: "bg-blue-500" },
      { label: "Applied", date: "Oct 15, 2023", icon: "send", color: "bg-slate-400" },
    ],
  },
  {
    id: 4,
    role: "Product Designer",
    company: "Airbnb",
    location: "San Francisco, CA",
    workType: "On-site",
    appliedDate: "Sep 28, 2023",
    salary: "$160k - $190k",
    status: "Rejected",
    initial: "A",
    gradientFrom: "from-slate-500",
    gradientTo: "to-slate-700",
    accentColor: "bg-red-500/60",
    description:
      "Help shape the visual and interaction design of Airbnb's hosting and travel products, used by millions of people around the world.",
    responsibilities: [
      "Lead end-to-end design for key product features.",
      "Conduct user research and usability testing.",
      "Create high-fidelity prototypes in Figma.",
      "Partner closely with engineering and product teams.",
    ],
    requirements: [
      "4+ years product design experience.",
      "Strong portfolio demonstrating UX and visual design.",
      "Proficiency in Figma and prototyping tools.",
      "Experience designing for mobile and web.",
    ],
    benefits: [
      "Travel credits for Airbnb stays.",
      "Comprehensive benefits package.",
      "Creative and collaborative environment.",
      "Annual offsite retreats.",
    ],
    matchScore: 58,
    matchLabel: "Partial Match",
    matchColor: "text-slate-400",
    statusHistory: [
      { label: "Rejected", date: "Oct 10, 2023", icon: "cancel", color: "bg-red-500" },
      { label: "Applied", date: "Sep 28, 2023", icon: "send", color: "bg-slate-400" },
    ],
  },
  {
    id: 5,
    role: "Senior Software Engineer",
    company: "Google",
    location: "Mountain View, CA",
    workType: "Remote",
    appliedDate: "Oct 24, 2023",
    salary: "$180k - $240k",
    status: "Interview",
    initial: "G",
    gradientFrom: "from-blue-500",
    gradientTo: "to-purple-500",
    accentColor: "bg-amber-500/80",
    description:
      "We are looking for a Senior Software Engineer to join our infrastructure team, building highly scalable systems that power billions of users globally.",
    responsibilities: [
      "Design and implement large-scale distributed systems.",
      "Lead technical discussions and drive architecture decisions.",
      "Collaborate with cross-functional teams to deliver product features.",
      "Mentor junior engineers and foster a culture of engineering excellence.",
    ],
    requirements: [
      "7+ years of software engineering experience.",
      "Proficiency in Go, Java, or C++.",
      "Experience with distributed systems and cloud infrastructure.",
      "Strong problem-solving and communication skills.",
    ],
    benefits: [
      "Competitive salary and RSU package.",
      "World-class health benefits.",
      "On-site amenities and flexible remote work.",
      "Annual education reimbursement.",
    ],
    matchScore: 82,
    matchLabel: "High Match",
    matchColor: "text-emerald-500",
    statusHistory: [
      { label: "Interview Scheduled", date: "Oct 27, 2023", icon: "chat_bubble", color: "bg-amber-500" },
      { label: "Application Reviewed", date: "Oct 25, 2023", icon: "check_circle", color: "bg-blue-500" },
      { label: "Applied", date: "Oct 24, 2023", icon: "send", color: "bg-slate-400" },
    ],
  },
];

export const STATUS_FILTERS = ["All", "Applied", "Interview", "Offer", "Rejected"];

export const STATUS_CONFIG = {
  Interview: {
    pill: "bg-amber-100 text-amber-700 dark:bg-amber-500/10 dark:text-amber-400 border border-amber-200 dark:border-amber-500/20",
    dot: "bg-amber-500 animate-pulse",
    bar: "bg-amber-500/80",
  },
  Applied: {
    pill: "bg-blue-100 text-blue-700 dark:bg-blue-500/10 dark:text-blue-400 border border-blue-200 dark:border-blue-500/20",
    dot: null,
    bar: "bg-blue-500/80",
  },
  Offer: {
    pill: "bg-emerald-100 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-500/20",
    dot: null,
    bar: "bg-emerald-500/80",
    icon: "check",
  },
  Rejected: {
    pill: "bg-red-100 text-red-700 dark:bg-red-500/10 dark:text-red-400 border border-red-200 dark:border-red-500/20",
    dot: null,
    bar: "bg-red-500/60",
  },
};